//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all te_npetestclientapi Suite Tests

//
LOAD_SUITE te_npetestclientapi
//

START_TESTCASE LBS-NPETESTCLIENTAPI-LocReq-0001
//!@SYMTestCaseID	LBS-NPETESTCLIENTAPI-LocReq-0001
RUN_TEST_STEP 300 te_npetestclientapi NpeTestClientApiLocReqStep
END_TESTCASE LBS-NPETESTCLIENTAPI-LocReq-0001

PRINT Complete te_npetestclientapi Suite Tests
