//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT run all te_suplrrlpasn suite Tests

//
LOAD_suite te_suplrrlpasnsuite -SharedData
//



START_TESTCASE                LBS-UT-SUPLRRLPASN-0001
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0001
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn0step c:\testdata\configs\te_suplrrlpasnsuite.ini Section0
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0001



START_TESTCASE                LBS-UT-SUPLRRLPASN-0002
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0002
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn1step c:\testdata\configs\te_suplrrlpasnsuite.ini Section1
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0002



START_TESTCASE                LBS-UT-SUPLRRLPASN-0003
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0003
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn2step c:\testdata\configs\te_suplrrlpasnsuite.ini Section2
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0003



START_TESTCASE                LBS-UT-SUPLRRLPASN-0004
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0004
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn3step c:\testdata\configs\te_suplrrlpasnsuite.ini Section3
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0004



START_TESTCASE                LBS-UT-SUPLRRLPASN-0005
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0005
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn4step c:\testdata\configs\te_suplrrlpasnsuite.ini Section4
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0005



START_TESTCASE                LBS-UT-SUPLRRLPASN-0006
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0006
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn5step c:\testdata\configs\te_suplrrlpasnsuite.ini Section5
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0006



START_TESTCASE                LBS-UT-SUPLRRLPASN-0007
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0007
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn6step c:\testdata\configs\te_suplrrlpasnsuite.ini Section6
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0007



START_TESTCASE                LBS-UT-SUPLRRLPASN-0008
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0008
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn7step c:\testdata\configs\te_suplrrlpasnsuite.ini Section7
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0008



START_TESTCASE                LBS-UT-SUPLRRLPASN-0009
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0009
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn8step c:\testdata\configs\te_suplrrlpasnsuite.ini Section8
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0009



START_TESTCASE                LBS-UT-SUPLRRLPASN-0010
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0010
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn9step c:\testdata\configs\te_suplrrlpasnsuite.ini Section9
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0010



START_TESTCASE                LBS-UT-SUPLRRLPASN-0011
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0011
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn10step c:\testdata\configs\te_suplrrlpasnsuite.ini Section10
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0011



START_TESTCASE                LBS-UT-SUPLRRLPASN-0012
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0012
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn11step c:\testdata\configs\te_suplrrlpasnsuite.ini Section11
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0012



START_TESTCASE                LBS-UT-SUPLRRLPASN-0013
//! @SYMTestCaseID              LBS-UT-SUPLRRLPASN-0013
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpasnsuite suplrrlpasn12step c:\testdata\configs\te_suplrrlpasnsuite.ini Section12
END_TESTCASE                  LBS-UT-SUPLRRLPASN-0013



PRINT completed_te_suplrrlpasn_tests
