// Copyright (c) 2001-2009 Objective Systems, Inc. (http://www.obj-sys.com) 
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available 
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//

/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).
 */
#ifndef SUPL_END_H
#define SUPL_END_H

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1PerCppTypes.h"
#include "ULP-Components.h"

/**
 * Header file for ASN.1 module SUPL-END
 */
/**************************************************************/
/*                                                            */
/*  SUPLEND                                                   */
/*                                                            */
/**************************************************************/

#define TV_SUPLEND	(TM_UNIV|TM_CONS|16)

struct ASN1T_SUPLEND {
   struct {
      unsigned positionPresent : 1;
      unsigned statusCodePresent : 1;
      unsigned verPresent : 1;
   } m;
   ASN1T_Position position;
   ASN1T_StatusCode statusCode;
   ASN1T_Ver ver;
   IMPORT_C ASN1T_SUPLEND ();
} ;

IMPORT_C int asn1PE_SUPLEND (OSCTXT* pctxt, ASN1T_SUPLEND* pvalue);

IMPORT_C int asn1PD_SUPLEND (OSCTXT* pctxt, ASN1T_SUPLEND* pvalue);

IMPORT_C void asn1Print_SUPLEND
   (const char* name, ASN1T_SUPLEND* pvalue);

IMPORT_C void asn1Free_SUPLEND (OSCTXT *pctxt, ASN1T_SUPLEND* pvalue);

#endif
