//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all te_suplconnectionmanager Suite Tests

//
LOAD_SUITE te_suplconnectionmanagerSuite -SharedData



START_TESTCASE                LBS-UT-SimpleConnection-0001
//! @SYMTestCaseID              LBS-UT-SimpleConnection-0001
//! @SYMTestType                UT
//! @SYMCreationDate            31/7/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite LbsStep_InstallScheduler  c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite suplconnectionmanager0Step c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
END_TESTCASE                  LBS-UT-SimpleConnection-0001


START_TESTCASE                LBS-UT-Molr-0001
//! @SYMTestCaseID              LBS-UT-Molr-0001
//! @SYMTestType                UT
//! @SYMCreationDate            31/7/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite LbsStep_InstallScheduler  c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite suplconnectionmanager1Step c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
END_TESTCASE                  LBS-UT-Molr-0001


START_TESTCASE                LBS-UT-MoLr_Twice-0001
//! @SYMTestCaseID              LBS-UT-MoLr_Twice-0001
//! @SYMTestType                UT
//! @SYMCreationDate            31/7/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite LbsStep_InstallScheduler  c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
RUN_TEST_STEP 100 te_suplconnectionmanagerSuite suplconnectionmanager3Step c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
END_TESTCASE                  LBS-UT-MoLr_Twice-0001


START_TESTCASE                LBS-UT-TimeOutTest-0001
//! @SYMTestCaseID              LBS-UT-TimeOutTest-0001
//! @SYMTestType                UT
//! @SYMCreationDate            31/7/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplconnectionmanagerSuite LbsStep_InstallScheduler  c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
//RUN_TEST_STEP 360 te_suplconnectionmanagerSuite suplconnectionmanager2Step c:\testdata\configs\te_suplconnectionmanagerSuite.ini Section0
END_TESTCASE                  LBS-UT-TimeOutTest-0001



