//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all te_agpshybridmodule Suite Tests

//
LOAD_SUITE te_agpshybridmoduleSuite
//

START_TESTCASE LBS-AgpsHybrid-LocationRequest-0001
//!@SYMTestCaseID	LBS-AgpsHybrid-LocationRequest-0001
RUN_TEST_STEP 1500 te_agpshybridmoduleSuite LocationRequestStep
END_TESTCASE LBS-AgpsHybrid-LocationRequest-0001


START_TESTCASE LBS-AgpsHybrid-AssistanceData-0001
//!@SYMTestCaseID	LBS-AgpsHybrid-AssistanceData-0001
RUN_TEST_STEP 1500 te_agpshybridmoduleSuite AssistanceDataStep
END_TESTCASE LBS-AgpsHybrid-AssistanceData-0001

PRINT Complete te_agpshybridmodule Suite Tests
