//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all te_suplrrlp Suite Tests

//
LOAD_SUITE te_suplrrlpSuite -SharedData
//


//Please add or make change of you test steps, here is sample only:

START_TESTCASE                LBS-UT-SuplRRLP-0001
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0001
//! @SYMTestType                UT
//! @SYMCreationDate            31/7/2008
//! @SYMAuthor                  Brajendras
RUN_TEST_STEP 360 te_suplrrlpSuite suplrrlp0Step c:\testdata\configs\te_suplrrlpSuite.ini Section0
END_TESTCASE                  LBS-UT-SuplRRLP-0001



//START_TESTCASE                LBS-UT-SuplRRLP-0002
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0002
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp1Step c:\testdata\configs\te_suplrrlpSuite.ini Section1
//END_TESTCASE                  LBS-UT-SuplRRLP-0002



//START_TESTCASE                LBS-UT-SuplRRLP-0003
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0003
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp2Step c:\testdata\configs\te_suplrrlpSuite.ini Section2
//END_TESTCASE                  LBS-UT-SuplRRLP-0003



//START_TESTCASE                LBS-UT-SuplRRLP-0004
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0004
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp3Step c:\testdata\configs\te_suplrrlpSuite.ini Section3
//END_TESTCASE                  LBS-UT-SuplRRLP-0004



//START_TESTCASE                LBS-UT-SuplRRLP-0005
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0005
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp4Step c:\testdata\configs\te_suplrrlpSuite.ini Section4
//END_TESTCASE                  LBS-UT-SuplRRLP-0005



//START_TESTCASE                LBS-UT-SuplRRLP-0006
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0006
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp5Step c:\testdata\configs\te_suplrrlpSuite.ini Section5
//END_TESTCASE                  LBS-UT-SuplRRLP-0006



//START_TESTCASE                LBS-UT-SuplRRLP-0007
//! @SYMTestCaseID              LBS-UT-SuplRRLP-0007
//! @SYMTestType                UT
//! @SYMCreationDate            1/8/2008
//! @SYMAuthor                  Brajendras
//RUN_TEST_STEP 100 te_suplrrlpSuite suplrrlp6Step c:\testdata\configs\te_suplrrlpSuite.ini Section6
//END_TESTCASE                  LBS-UT-SuplRRLP-0007



PRINT Complate_te_suplrrlp_Tests

